### ISSUE TITLE
3D Modeling - Fish String

### ISSUE THREAD

**Issue by Leong15** [ChisanaKita/FYP#10]
3D model fishing string for development

- [ ] Design
- [ ] Modeling
- [ ] QA

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/103549027-ace18100-4ee1-11eb-890e-f6caf6e696bf.png)

**Comment by ChisanaKita** [comment]
Um... IDK if this is necessary. By fish string I'm referring to fishing string and that is done by using Unity to draw lines.
Closing it now.

**Comment by ChisanaKita** [comment]
![image](https://user-images.githubusercontent.com/29787181/103567786-63079380-4eff-11eb-9ad6-6e2e4f64f111.png)
