### ISSUE TITLE
[v0.1] 3D Modeling - Generic Fishing Rod + Reel

### ISSUE THREAD

**Issue by ChisanaKita** [ChisanaKita/FYP#4]
3D model a generic fishing rod and reel for development

- [x] Design
- [x] Modeling
- [x] QA

**Comment by Leong15** [comment]
This picture just shows you what part gonna have in the fishing rod. The style of the rod, I will make it more realistic.
![FishingRod1](https://user-images.githubusercontent.com/53085228/95995087-a05e0700-0e63-11eb-92c5-09500f39a98d.png)

**Comment by ChisanaKita** [comment]
> This picture just shows you what part gonna have in the fishing rod. The style of the rod, I will make it more realistic.

Would you able to model the reel as well? 
If so, you gonna model them separately.
e.g :  the rod itself, the reel and the handel 
I wanted them to be standalone parts so players have the option to upgrade different parts of their rod.

**Comment by Leong15** [comment]
Is that mean I need to model them in different projects? Or I model them in one project but don't make them stick together?

**Comment by ChisanaKita** [comment]
> Is that mean I need to model them in different projects? Or I model them in one project but don't make them stick together?

Together in the same project but not connected, and be sure to place them in the correct position.

**Comment by Leong15** [comment]
Ok, I can do that.

**Comment by ChisanaKita** [comment]
@Leong15 New order : 
The fishing rod should separate to 3 models
- The rod
- The reel
- The handle

Please set the handle's center point correctly.

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/101450310-537b4600-3965-11eb-9034-3e881821ed33.png)
The top of the rod
![image](https://user-images.githubusercontent.com/53085228/101450320-583ffa00-3965-11eb-8385-241bfe4e5894.png)
The bottom of the rod

**Comment by ChisanaKita** [comment]
Will check it out tmr

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/103137682-f8d43f00-4705-11eb-9b1d-0b8a2cfdc3d6.png)
Back
![image](https://user-images.githubusercontent.com/53085228/103137692-0ee1ff80-4706-11eb-9383-67508b00a066.png)
Left
The reel of the fishing rod. There is a holder to link the reel and the rod.
The holder and the reel are split.
That means when the reel is rotating the holder will not follow

**Comment by ChisanaKita** [comment]
Can you re-do the reel?
Reference : https://fishingbooker.com/blog/types-of-fishing-reels/

**Comment by Leong15** [comment]
ok sure

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/103541999-3b043a00-4ed7-11eb-80e8-e93bd620ec56.png)
Right
![image](https://user-images.githubusercontent.com/53085228/103542036-4b1c1980-4ed7-11eb-80f6-e709b7751d1f.png)
Back
![image](https://user-images.githubusercontent.com/53085228/103542084-5cfdbc80-4ed7-11eb-9a22-bbe14f4b663b.png)
Left
![image](https://user-images.githubusercontent.com/53085228/103542195-8ae30100-4ed7-11eb-8545-6e259ad8f42f.png)
![image](https://user-images.githubusercontent.com/53085228/103542156-7999f480-4ed7-11eb-8f09-0adc555e801e.png)

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/103542305-b4039180-4ed7-11eb-8768-c1d53180ab96.png)

**Comment by ChisanaKita** [comment]
![image](https://user-images.githubusercontent.com/29787181/103567209-53d41600-4efe-11eb-8a3c-e97828c87659.png)

Liking it so far!
BTW, can you make it shorter and also make a handle please?
P.S. : The handle must be made with 3 parts, Please refer to the picture above.

**Comment by ChisanaKita** [comment]
- Make it shorter
- Separating the body
- Make a handle

**Comment by Leong15** [comment]
![image](https://user-images.githubusercontent.com/53085228/103629799-bcada380-4f7b-11eb-9b0b-38e836cc7823.png)
![image](https://user-images.githubusercontent.com/53085228/103629838-cafbbf80-4f7b-11eb-8b7b-50d07d1c31b8.png)
The handle

**Comment by ChisanaKita** [comment]
Finished
