### ISSUE TITLE
[Mega-Thread] Documentations - Project Interim Report

### ISSUE THREAD

**Issue by ChisanaKita** [ChisanaKita/FYP#8]
Deadline : 8 Jan 2021 (As version 0.5)

## Document TODO List
- [x] Create report file (@ChisanaKita) (See Wiki)
- [x] Draft report structure
- [x] Abstract
- [x] Table of Content
- [x] Table of Figures
- [x] Introduction
  - [x] State the goals of the game
  - [x] Document Structure
- [x] Game Design 
  - [x] List of the basic constraints and requirements
  - [x] Design Thinking 
- [x] Game Overview
  - [x] Story background
  - [x] Play modes
  - [x] System Architecture 
- [x] Game World
  - [x] Game Environment
  - [x] Level Design
  - [x] Maps Design
  - [x] Characters
- [x] Objects 
- [x] Gameplay Description
  - [x] User Interface Design
  - [x] Control
- [x] Software Design
  - [x] Use Case Diagram
  - [x] Class Diagrams
  - [x] Sequence Diagrams
- [x] Hardware and Software Requirements
- [x] Technical Considerations
- [x] Project Plan
  - [x] Schedule
  - [x] Milestone description
  - [x] Action Plan
- [x] References
- [x] Appendices
  - [x] Workload Distribution
  - [x] Budget Estimation
  - [x] Log Sheets
- [x] QA
  - [x] Final check by : @ChisanaKita 
  - [x] Supervisor feed back
  - [x] fixes (If any)
## PPT DOTO List
- [x] Create PPT file (@ChisanaKita) (See Wiki)
- [x] Draft structure
- [x] Contents
- [x] QA
  - [x] Final check by : @ChisanaKita 
  - [x] Supervisor feed back
  - [x] fixes (If any)

**Comment by Leong15** [comment]
Use case: go home, go to market, choose game level(map),  buy resources, selling fish, eat food, fishing, Open Radio, Open Mp3, 
               choose Music

I draw a simple version, but I have one question.

 what resources can buy in the market? Like fishing bait, food. However, how about radio and mp3. Are they need to buy or a function for players when they fishing? 

If you have other use case want to put in can enter in here or you think some use case I draw is not correct tell me here too.

**Comment by ChisanaKita** [comment]
Use case diagram is about in a set of environment, what's the actions that the players can do. So, just list all the available actions in-game

**Comment by ChisanaKita** [comment]
Reference : https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-use-case-diagram/
You should make the use case and maybe talk about the diagrams in the presentation?
